---
# tasks file for ansible-my-fedora
# Setup my Fedora Laptop

- name: fedora-workstation-repositories
  become: yes
  ansible.builtin.dnf:
    name:
      - fedora-workstation-repositories
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install basic packages
  become: yes
  ansible.builtin.dnf:
    name: "{{ basic_packages }}"
    state: present

- name: Install Dev and Ops tools
  tags:
    - dev
    - never
  block:
    - name: Add VS Code repository
      become: yes
      tags:
        - never
        - dev
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes

    - name: Azure CLI repository
      tags:     description,
        - dev   
        - never
      ansible.builtin.yum_repository:
        name: azure-cli
        description: Azure CLI repository
        baseurl: https://packages.microsoft.com/yumrepos/azure-cli
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes
      become: yes

    - name: Install Dev and Ops packages
      ansible.builtin.dnf:
        name: "{{ dev_tools }}"
        state: present
      become: yes


- name: Install systools packages
  become: yes
  tags:
    - systools
    - never
  ansible.builtin.dnf:
    name: "{{ sys_tools }}"
    state: present


- name: Remove unwanted Packages
  become: yes
  tags:
    - unwanted
    - uninstall
    - remove
    - never
  ansible.builtin.dnf:
    name: "{{ unwanted_packages }}"
    state: absent

- name: Install packages without gpg check
  become: yes
  tags:
    - localinistall
    - never
  ansible.builtin.dnf:
    name: "{{ direct_install }}"
    state: present
    disable_gpg_check: yes

- name: Install Flatpaks
  become: no
  tags:
    - flatpak
    - never
  block:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install multiple packages
      community.general.flatpak:
        name: "{{ flatpaks }}"
        remote: "flathub"
        method: "user"


- name: Install Games
  tags:
    - games
    - never
  ansible.builtin.dnf:
    name: "{{ games }}"
    state: present

- name: Tweak my desktop
  become: no
  tags:
    - tweak
    - never
  block:
    - name: Touchpad tap as click
      community.general.dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
        value: "true"

    - name: Nautilus - sort folders before files
      community.general.dconf:
        key: "/org/gtk/settings/file-chooser/sort-directories-first"
        value: "true"

    - name: Configure available keyboard layouts in Gnome
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'ara')]"
        state: present

    - name: Configure available keyboard layouts in Gnome
      community.general.dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
        value: "['<Alt>Shift_L']"
        state: present

- name: install all updates
  become: yes
  tags:
    - update
    - upgrade
  ansible.builtin.yum:
    name: '*'
    update_cache: yes
    state: latest
