---
# tasks file for ansible-my-fedora
# Setup my Fedora Laptop

- hosts: localhost
  connection: local
  vars_files:
    - ../defaults/main.yml
  tasks:
    - debug:
        msg: Setup my Fedora Laptop
    - name: install required repositories
      include_tasks: repos.yml
    - name: Install basic packages
      include_tasks: packages.yml
    - name: install Dev and Ops tools
      include_tasks: dev.yml
    - name: Tweak my desktop
      include_tasks: desktop-config.yml
    - debug:
        msg: Uninstalling unwanted packages
    - name: remove unwanted apps
      include_tasks: uninstall.yml
