---
- name: Add VS Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  become: yes

- name: Add Fortinet repository
  yum_repository:
    name: forticlient
    description: Forticlient Repo
    baseurl: https://repo.fortinet.com/repo/6.4/centos/7/os/x86_64
    gpgkey: https://repo.fortinet.com/repo/6.4/centos/7/os/x86_64/RPM-GPG-KEY
    gpgcheck: yes
  become: yes

- name: fedora-workstation-repositories and other direct installation
  package:
    name:
      - fedora-workstation-repositories
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  become: yes

- name: install all updates
  package:
    name: '*'
    update_cache: yes
    state: latest
  become: yes
