---
- name: Remove unneeded Packages
  yum:
    name:
      - gnome-boxes
    state: absent
  become: yes

- name: Remove unwanted Packages
  package:
    name:
      - rhythmbox
      - virtualbox-guest-additions
    state: absent
  become: yes
