---
- name: Add the flathub flatpak repository remote to the user installation
  become: false
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install multiple packages
  become: false
  community.general.flatpak:
    name: "{{ flatpaks }}"
    remote: "flathub"
    method: "user"
