---
- name: Add VS Code repository
  tags:
    - never
    - dev
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  become: yes

- name: Import Fortinet GPG key from a url
  become: yes
  tags:
    - vpn
    - never
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.fortinet.com/repo/centos/7/os/x86_64/RPM-GPG-KEY

- name: fedora-workstation-repositories and other direct installation
  ansible.builtin.yum:
    name:
      - fedora-workstation-repositories
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  become: yes

# - name: Kubernetes repo
#   become: yes
#   tags:
#     - dev
#     - never
#   ansible.builtin.yum_repository:
#     name: kubernetes
#     description: kubernetes client tools repo
#     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
#     enabled: true
#     gpgcheck: yes
#     gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Azure CLI repository
  tags:     description,
    - dev   
    - never
  ansible.builtin.yum_repository:
    name: azure-cli
    description: Azure CLI repository
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  become: yes

- name: install all updates
  ansible.builtin.yum:
    name: '*'
    update_cache: yes
    state: latest
  become: yes
